# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from scout_mini_msgs/FaultState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FaultState(genpy.Message):
  _md5sum = "a52d9af2999a855a1496f62180e48a82"
  _type = "scout_mini_msgs/FaultState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool battery_under_voltage_failure
bool battery_under_voltage_alarm 
bool loss_remote_control"""
  __slots__ = ['battery_under_voltage_failure','battery_under_voltage_alarm','loss_remote_control']
  _slot_types = ['bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       battery_under_voltage_failure,battery_under_voltage_alarm,loss_remote_control

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FaultState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.battery_under_voltage_failure is None:
        self.battery_under_voltage_failure = False
      if self.battery_under_voltage_alarm is None:
        self.battery_under_voltage_alarm = False
      if self.loss_remote_control is None:
        self.loss_remote_control = False
    else:
      self.battery_under_voltage_failure = False
      self.battery_under_voltage_alarm = False
      self.loss_remote_control = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.battery_under_voltage_failure, _x.battery_under_voltage_alarm, _x.loss_remote_control))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.battery_under_voltage_failure, _x.battery_under_voltage_alarm, _x.loss_remote_control,) = _get_struct_3B().unpack(str[start:end])
      self.battery_under_voltage_failure = bool(self.battery_under_voltage_failure)
      self.battery_under_voltage_alarm = bool(self.battery_under_voltage_alarm)
      self.loss_remote_control = bool(self.loss_remote_control)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.battery_under_voltage_failure, _x.battery_under_voltage_alarm, _x.loss_remote_control))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.battery_under_voltage_failure, _x.battery_under_voltage_alarm, _x.loss_remote_control,) = _get_struct_3B().unpack(str[start:end])
      self.battery_under_voltage_failure = bool(self.battery_under_voltage_failure)
      self.battery_under_voltage_alarm = bool(self.battery_under_voltage_alarm)
      self.loss_remote_control = bool(self.loss_remote_control)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
