// Generated by gencpp from file scout_mini_msgs/LightState.msg
// DO NOT EDIT!


#ifndef SCOUT_MINI_MSGS_MESSAGE_LIGHTSTATE_H
#define SCOUT_MINI_MSGS_MESSAGE_LIGHTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace scout_mini_msgs
{
template <class ContainerAllocator>
struct LightState_
{
  typedef LightState_<ContainerAllocator> Type;

  LightState_()
    : header()
    , control_enable(false)
    , mode()
    , brightness(0)  {
    }
  LightState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , control_enable(false)
    , mode(_alloc)
    , brightness(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _control_enable_type;
  _control_enable_type control_enable;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mode_type;
  _mode_type mode;

   typedef uint8_t _brightness_type;
  _brightness_type brightness;





  typedef boost::shared_ptr< ::scout_mini_msgs::LightState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scout_mini_msgs::LightState_<ContainerAllocator> const> ConstPtr;

}; // struct LightState_

typedef ::scout_mini_msgs::LightState_<std::allocator<void> > LightState;

typedef boost::shared_ptr< ::scout_mini_msgs::LightState > LightStatePtr;
typedef boost::shared_ptr< ::scout_mini_msgs::LightState const> LightStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scout_mini_msgs::LightState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scout_mini_msgs::LightState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scout_mini_msgs::LightState_<ContainerAllocator1> & lhs, const ::scout_mini_msgs::LightState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.control_enable == rhs.control_enable &&
    lhs.mode == rhs.mode &&
    lhs.brightness == rhs.brightness;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scout_mini_msgs::LightState_<ContainerAllocator1> & lhs, const ::scout_mini_msgs::LightState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scout_mini_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scout_mini_msgs::LightState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scout_mini_msgs::LightState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scout_mini_msgs::LightState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scout_mini_msgs::LightState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout_mini_msgs::LightState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout_mini_msgs::LightState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scout_mini_msgs::LightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b58f85563977207a3123a9b2ba0e669d";
  }

  static const char* value(const ::scout_mini_msgs::LightState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb58f85563977207aULL;
  static const uint64_t static_value2 = 0x3123a9b2ba0e669dULL;
};

template<class ContainerAllocator>
struct DataType< ::scout_mini_msgs::LightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scout_mini_msgs/LightState";
  }

  static const char* value(const ::scout_mini_msgs::LightState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scout_mini_msgs::LightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"bool control_enable  # Lighting control enable flag\n"
"\n"
"string mode       # The current mode (ON, OFF, BL, CUSTOM)\n"
"uint8 brightness  # The current brightness of light (0 - 100)\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::scout_mini_msgs::LightState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scout_mini_msgs::LightState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.control_enable);
      stream.next(m.mode);
      stream.next(m.brightness);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scout_mini_msgs::LightState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scout_mini_msgs::LightState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "control_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control_enable);
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mode);
    s << indent << "brightness: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brightness);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCOUT_MINI_MSGS_MESSAGE_LIGHTSTATE_H
