(cl:in-package scout_mini_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRIVER_VOLTAGE-VAL
          DRIVER_VOLTAGE
          DRIVER_TEMPERATURE-VAL
          DRIVER_TEMPERATURE
          COMMUNICATION_FAILURE-VAL
          COMMUNICATION_FAILURE
          LOW_SUPPLY_VOLTAGE-VAL
          LOW_SUPPLY_VOLTAGE
          MOTOR_OVER_TEMPERATURE-VAL
          MOTOR_OVER_TEMPERATURE
          DRIVER_OVER_CURRENT-VAL
          DRIVER_OVER_CURRENT
          DRIVER_OVER_TEMPERATURE-VAL
          DRIVER_OVER_TEMPERATURE
))